[package]
name = "gassetsmaker"
version = "0.1.0"
edition = "2021"


[dependencies]
image = "0.24"
glob = "0.3"
zip = "2"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4", features = ["derive"] }

